### ISSUE TITLE
α版:⑤マイページ（全体、SNS向けOGP）

### ISSUE THREAD

**Issue by Yoosuke** [bright-org/bright#27]
下記も確認ができて終了とする

- [x] デモができるレベルのデザイン移植
- [x] デモができるレベルのリンクを作成
- [x] 最終デザインフィックス
- [x] SNS向けOGP

関連チケット　
- [x] [OGP:⑤マイページ（全体、SNS向けOGP）#564](https://github.com/bright-org/bright/issues/564) 
- [ ] [プロフィール仕様/「関わっているユーザー」内のユーザー表示：⑤マイページ（全体、SNS向けOGP）#238](https://github.com/bright-org/bright/issues/238)
  　└「運営のみ実装：テーブル再設計から」
- [x] [重要な連絡：⑤マイページ（全体、SNS向けOGP）#243](https://github.com/bright-org/bright/issues/243)　

- [x]  さまざまな人たちと交流は　運営公式もβ扱いになりましたので、実質カードの枠のみαリリースする

- [x] [保有スキル：⑤マイページ（全体、SNS向けOGP）#245](https://github.com/bright-org/bright/issues/245)
- [x] [関わっているチーム：⑤マイページ（全体、SNS向けOGP）#246](https://github.com/bright-org/bright/issues/246)
- [x] [関わっているユーザー ：⑤マイページ（全体、SNS向けOGP）#247](https://github.com/bright-org/bright/issues/247)
