### ISSUE TITLE
β版:⑤マイページ（全体、SNS向けOGP）

### ISSUE THREAD

**Issue by ymn-t-yamanashi** [bright-org/bright#707]
- [ ] [スキルセットジェム（値を代入部分）：⑤マイページ（全体、SNS向けOGP）#242](https://github.com/bright-org/bright/issues/242)
- [ ]   [重要な連絡：⑤マイページ（全体、SNS向けOGP）#243](https://github.com/bright-org/bright/issues/243)
- [ ] [さまざまな人たとの交流：⑤マイページ（全体、SNS向けOGP）#244](https://github.com/bright-org/bright/issues/244)
- [ ] [関わっているチーム：⑤マイページ（全体、SNS向けOGP）#246](https://github.com/bright-org/bright/issues/246)
- [ ] [関わっているユーザー ：⑤マイページ（全体、SNS向けOGP）#247](https://github.com/bright-org/bright/issues/247)
